// French Gregorian Calendar Name Days (Fêtes traditionnelles du calendrier grégorien)
// Permet de déterminer la fête à célébrer pour chaque jour de l'année.

export const nameDays: Record<number, Record<number, string[]>> = {
  1: { // Janvier
    1: ["Jour de l'An"],
    2: ["Basile"],
    3: ["Geneviève"],
    4: ["Odilon"],
    5: ["Edouard"],
    6: ["Balthazar", "Melchior", "Gaspard", "Épiphanie"],
    7: ["Raymond"],
    8: ["Lucien"],
    9: ["Alix"],
    10: ["Guillaume"],
    11: ["Pauline"],
    12: ["Tatiana"],
    13: ["Yvette"],
    14: ["Nina"],
    15: ["Rémi"],
    16: ["Marcel"],
    17: ["Roseline"],
    18: ["Prisca"],
    19: ["Marius"],
    20: ["Sébastien"],
    21: ["Agnès"],
    22: ["Vincent"],
    23: ["Barnard"],
    24: ["François de Sales"],
    25: ["Conversion de Paul"],
    26: ["Paule"],
    27: ["Angèle"],
    28: ["Thomas d'Aquin"],
    29: ["Gildas"],
    30: ["Martine"],
    31: ["Marcelle"]
  },
  2: { // Février
    1: ["Ella"],
    2: ["Présentation", "Chandeleur"],
    3: ["Blaise"],
    4: ["Véronique"],
    5: ["Agathe"],
    6: ["Gaston"],
    7: ["Eugénie"],
    8: ["Jacqueline"],
    9: ["Apolline"],
    10: ["Arnaud"],
    11: ["Notre-Dame de Lourdes"],
    12: ["Félix"],
    13: ["Béatrice"],
    14: ["Valentin"],
    15: ["Claude"],
    16: ["Julienne"],
    17: ["Alexis"],
    18: ["Bernadette"],
    19: ["Gabin"],
    20: ["Aimée"],
    21: ["Damien"],
    22: ["Isabelle"],
    23: ["Lazare"],
    24: ["Modeste"],
    25: ["Roméo"],
    26: ["Nestor"],
    27: ["Honorine"],
    28: ["Romain"],
    29: ["Auguste"]
  },
  3: { // Mars
    1: ["Aubin"],
    2: ["Charles le Bon"],
    3: ["Guénolé"],
    4: ["Casimir"],
    5: ["Olive"],
    6: ["Colette"],
    7: ["Félicité"],
    8: ["Jean de Dieu"],
    9: ["Françoise"],
    10: ["Vivien"],
    11: ["Rosine"],
    12: ["Justine"],
    13: ["Rodrigue"],
    14: ["Mathilde"],
    15: ["Louise"],
    16: ["Bénédicte"],
    17: ["Patrice"],
    18: ["Cyrille"],
    19: ["Joseph"],
    20: ["Herbert"],
    21: ["Clémence"],
    22: ["Léa"],
    23: ["Victorien"],
    24: ["Catherine de Suède"],
    25: ["Annonciation"],
    26: ["Larissa"],
    27: ["Habib"],
    28: ["Gontran"],
    29: ["Gwladys"],
    30: ["Amédée"],
    31: ["Benjamin"]
  },
  4: { // Avril
    1: ["Hugues"],
    2: ["Sandrine"],
    3: ["Richard"],
    4: ["Isidore"],
    5: ["Irène"],
    6: ["Marcellin"],
    7: ["Jean-Baptiste de la Salle"],
    8: ["Julie"],
    9: ["Gautier"],
    10: ["Fulbert"],
    11: ["Stanislas"],
    12: ["Jules"],
    13: ["Ida"],
    14: ["Maxime"],
    15: ["Paterne"],
    16: ["Benoît-Joseph"],
    17: ["Anicet"],
    18: ["Parfait"],
    19: ["Emma"],
    20: ["Odette"],
    21: ["Anselme"],
    22: ["Alexandre"],
    23: ["Georges"],
    24: ["Fidèle"],
    25: ["Marc"],
    26: ["Alida"],
    27: ["Zita"],
    28: ["Valérie"],
    29: ["Catherine de Sienne"],
    30: ["Robert"]
  },
  5: { // Mai
    1: ["Fête du Travail", "Jérémie"],
    2: ["Boris"],
    3: ["Philippe", "Jacques"],
    4: ["Sylvain"],
    5: ["Judith"],
    6: ["Prudence"],
    7: ["Gisèle"],
    8: ["Victoire 1945", "Désiré"],
    9: ["Pacôme"],
    10: ["Solange"],
    11: ["Estelle"],
    12: ["Achille"],
    13: ["Rolande"],
    14: ["Matthias"],
    15: ["Denise"],
    16: ["Honoré"],
    17: ["Pascal"],
    18: ["Eric"],
    19: ["Yves"],
    20: ["Bernardin"],
    21: ["Constantin"],
    22: ["Émile"],
    23: ["Didier"],
    24: ["Donatien"],
    25: ["Sophie"],
    26: ["Bérenger"],
    27: ["Augustin de Cantorbéry"],
    28: ["Germain"],
    29: ["Aymar"],
    30: ["Ferdinand"],
    31: ["Visitation"]
  },
  6: { // Juin
    1: ["Justin"],
    2: ["Blandine"],
    3: ["Kévin"],
    4: ["Clotilde"],
    5: ["Igor"],
    6: ["Norbert"],
    7: ["Gilbert"],
    8: ["Médard"],
    9: ["Diane"],
    10: ["Landry"],
    11: ["Barnabé"],
    12: ["Guy"],
    13: ["Antoine de Padoue"],
    14: ["Élisée"],
    15: ["Germaine"],
    16: ["Jean-François Régis"],
    17: ["Hervé"],
    18: ["Léonce"],
    19: ["Romuald"],
    20: ["Silvère"],
    21: ["Rodolphe"],
    22: ["Alban"],
    23: ["Audrey"],
    24: ["Jean-Baptiste"],
    25: ["Prosper"],
    26: ["Anthelme"],
    27: ["Fernand"],
    28: ["Irénée"],
    29: ["Pierre", "Paul"],
    30: ["Martial"]
  },
  7: { // Juillet
    1: ["Thierry"],
    2: ["Martinien"],
    3: ["Thomas"],
    4: ["Florent"],
    5: ["Antoine-Marie"],
    6: ["Mariette"],
    7: ["Raoul"],
    8: ["Thibaut"],
    9: ["Amandine"],
    10: ["Ulrich"],
    11: ["Benoît"],
    12: ["Olivier"],
    13: ["Henri", "Joël"],
    14: ["Camille"],
    15: ["Donald"],
    16: ["Notre-Dame du Mont-Carmel"],
    17: ["Charlotte"],
    18: ["Frédéric"],
    19: ["Arsène"],
    20: ["Marina"],
    21: ["Victor"],
    22: ["Marie-Madeleine"],
    23: ["Brigitte"],
    24: ["Christine"],
    25: ["Jacques"],
    26: ["Anne", "Joachim"],
    27: ["Nathalie"],
    28: ["Samson"],
    29: ["Marthe"],
    30: ["Juliette"],
    31: ["Ignace de Loyola"]
  },
  8: { // Août
    1: ["Alphonse"],
    2: ["Julien Eymard"],
    3: ["Lydie"],
    4: ["Jean-Marie Vianney"],
    5: ["Abel"],
    6: ["Transfiguration"],
    7: ["Gaétan"],
    8: ["Dominique"],
    9: ["Amour"],
    10: ["Laurent"],
    11: ["Claire"],
    12: ["Clarisse"],
    13: ["Hippolyte"],
    14: ["Evrard"],
    15: ["Assomption", "Marie"],
    16: ["Armel"],
    17: ["Hyacinthe"],
    18: ["Hélène"],
    19: ["Jean Eudes"],
    20: ["Bernard"],
    21: ["Christophe"],
    22: ["Fabrice"],
    23: ["Rose de Lima"],
    24: ["Barthélemy"],
    25: ["Louis"],
    26: ["Natacha"],
    27: ["Monique"],
    28: ["Augustin"],
    29: ["Sabine"],
    30: ["Fiacre"],
    31: ["Aristide"]
  },
  9: { // Septembre
    1: ["Gilles"],
    2: ["Ingrid"],
    3: ["Grégoire"],
    4: ["Rosalie"],
    5: ["Raïssa"],
    6: ["Bertrand"],
    7: ["Reine"],
    8: ["Nativité de la Vierge", "Adrien"],
    9: ["Alain"],
    10: ["Inès"],
    11: ["Adelphe"],
    12: ["Apollinaire"],
    13: ["Aimé"],
    14: ["La Sainte-Croix"],
    15: ["Roland"],
    16: ["Edith"],
    17: ["Renaud"],
    18: ["Nadège"],
    19: ["Émilie"],
    20: ["Davy"],
    21: ["Matthieu"],
    22: ["Maurice"],
    23: ["Constant"],
    24: ["Thècle"],
    25: ["Hermann"],
    26: ["Côme", "Damien"],
    27: ["Vincent de Paul"],
    28: ["Venceslas"],
    29: ["Michel", "Gabriel", "Raphaël"],
    30: ["Jérôme"]
  },
  10: { // Octobre
    1: ["Thérèse de l'Enfant-Jésus"],
    2: ["Léger"],
    3: ["Gérard"],
    4: ["François d'Assise"],
    5: ["Fleur"],
    6: ["Bruno"],
    7: ["Serge"],
    8: ["Pélagie"],
    9: ["Denis"],
    10: ["Ghislain"],
    11: ["Firmin"],
    12: ["Wilfried"],
    13: ["Géraud"],
    14: ["Juste"],
    15: ["Thérèse d'Avila"],
    16: ["Edwige"],
    17: ["Baudouin"],
    18: ["Luc"],
    19: ["René"],
    20: ["Adeline"],
    21: ["Céline"],
    22: ["Elodie"],
    23: ["Jean de Capistran"],
    24: ["Florentin"],
    25: ["Crépin"],
    26: ["Dimitri"],
    27: ["Émeline"],
    28: ["Jude"],
    29: ["Narcisse"],
    30: ["Bienvenue"],
    31: ["Quentin"]
  },
  11: { // Novembre
    1: ["Toussaint"],
    2: ["Défunts"],
    3: ["Hubert"],
    4: ["Charles"],
    5: ["Sylvie"],
    6: ["Bertille"],
    7: ["Carine"],
    8: ["Geoffroy"],
    9: ["Théodore"],
    10: ["Léon"],
    11: ["Armistice 1918", "Martin"],
    12: ["Christian"],
    13: ["Brice"],
    14: ["Sidoine"],
    15: ["Albert"],
    16: ["Marguerite"],
    17: ["Élisabeth"],
    18: ["Aude"],
    19: ["Tanguy"],
    20: ["Edmond"],
    21: ["Présentation de Marie"],
    22: ["Cécile"],
    23: ["Clément"],
    24: ["Flora"],
    25: ["Catherine"],
    26: ["Delphine"],
    27: ["Séverin"],
    28: ["Jacques de la Marche"],
    29: ["Saturnin"],
    30: ["André"]
  },
  12: { // Décembre
    1: ["Florence"],
    2: ["Viviane"],
    3: ["François-Xavier"],
    4: ["Barbara"],
    5: ["Gérald"],
    6: ["Nicolas"],
    7: ["Ambroise"],
    8: ["Immaculée Conception", "Elsa"],
    9: ["Pierre Fourier"],
    10: ["Romaric"],
    11: ["Daniel"],
    12: ["Jeanne-Françoise de Chantal"],
    13: ["Lucie"],
    14: ["Odile"],
    15: ["Ninon"],
    16: ["Alice"],
    17: ["Gaël"],
    18: ["Gatien"],
    19: ["Urbain"],
    20: ["Théophile"],
    21: ["Pierre Canisius"],
    22: ["Françoise-Xavière"],
    23: ["Armand"],
    24: ["Adèle"],
    25: ["Noël"],
    26: ["Étienne"],
    27: ["Jean"],
    28: ["Innocents"],
    29: ["David"],
    30: ["Roger"],
    31: ["Sylvestre"]
  }
};

export function lookupNameDay(month: number, day: number): string[] {
  return nameDays[month]?.[day] || [];
}
