name: Release & CI

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Debug Environment
        run: |
          node -v
          npm -v

      - name: Install Dependencies
        run: npm install --verbose --no-audit --no-fund



      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build Application
        run: npm run build

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --debug

      - name: Build and Push Docker Image
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          VERSION_NO_V=${VERSION#v}
          echo "Version found: $VERSION ($VERSION_NO_V)"
          
          echo "Logging in to Docker Registry..."
          docker login registry.robin-joseph.fr -u dummy -p dummy
          
          echo "Building Docker Image..."
          docker build --build-arg NEXT_PUBLIC_APP_VERSION=$VERSION_NO_V -t registry.robin-joseph.fr/ancestors:latest -t registry.robin-joseph.fr/ancestors:$VERSION -t registry.robin-joseph.fr/ancestors:$VERSION_NO_V .
          
          echo "Pushing Docker Images..."
          docker push registry.robin-joseph.fr/ancestors:latest
          docker push registry.robin-joseph.fr/ancestors:$VERSION
          docker push registry.robin-joseph.fr/ancestors:$VERSION_NO_V
